FROM python:3.11-slim

WORKDIR /app/backend


COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend .

COPY backend/entrypoint.sh /app/backend/entrypoint.sh
RUN chmod +x /app/backend/entrypoint.sh

EXPOSE 8000

CMD ["/app/backend/entrypoint.sh"]