# Generated by Django 5.0.2 on 2025-05-20 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_authuser_remove_doctor_user_remove_pacient_user_and_more'),
        ('turnos', '0002_especialidad_medico_turno_medico_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentification.authuser'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentification.authuser'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.authuser'),
        ),
    ]
